# ============================================================
# Page Object: MyExamPage
# Module: personnel
# Page: 我的考试 (my-exam)
# Author: generated by skill: page-object-generator
# ============================================================
from base.base_page import BasePage
from selenium.webdriver.common.by import By
from typing import List, Dict


class MyExamPage(BasePage):
    """
    我的考试页面 - 展示当前用户已分配或需完成的考试/测评列表。
    重构目标：严格遵守 skill 规范，无绝对XPath，无 time.sleep，无 print。
    """

    # ==================== Locators (来自 PAGE_CONTEXT.md，CSS优先) ====================
    # 搜索区
    EXAM_NAME_INPUT = (By.CSS_SELECTOR, "input[placeholder*='考试名称']")
    EXAM_STATUS_SELECT = (By.CSS_SELECTOR, ".el-select .el-select__wrapper")
    SEARCH_BTN = (By.XPATH, "//button[.//span[text()='搜索']]")
    RESET_BTN = (By.XPATH, "//button[.//span[text()='重置']]")

    # 表格区
    TABLE = (By.CSS_SELECTOR, ".el-table")
    TABLE_LOADING = (By.CSS_SELECTOR, ".el-loading-mask")
    TABLE_EMPTY = (By.CSS_SELECTOR, ".el-empty__description")
    TABLE_ROWS = (By.CSS_SELECTOR, ".el-table__body-wrapper tbody tr.el-table__row")

    # 操作列按钮 (动态XPath用于点击)
    # 通用方案，避免多个 locator

    # 分页区
    PAGINATION = (By.CSS_SELECTOR, ".el-pagination")
    PAGINATION_TOTAL = (By.CSS_SELECTOR, ".el-pagination__total")
    PAGINATION_PAGER = (By.CSS_SELECTOR, ".el-pager .number")

    # 考试详情弹窗
    DIALOG = (By.CSS_SELECTOR, ".el-dialog")
    DIALOG_TITLE = (By.CSS_SELECTOR, ".el-dialog__title")
    DIALOG_CLOSE_BTN = (By.CSS_SELECTOR, ".el-dialog__headerbtn")

    # 确认开始考试弹窗
    CONFIRM_DIALOG = (By.XPATH, "//div[contains(@class, 'el-dialog') and .//span[text()='确认开始考试']]")
    CONFIRM_SUBMIT_BTN = (By.XPATH, "//div[contains(@class, 'el-dialog__footer')]//button[.//span[text()='确定']]")
    CONFIRM_CANCEL_BTN = (By.XPATH, "//div[contains(@class, 'el-dialog__footer')]//button[.//span[text()='取消']]")

    # ==================== Core Methods ====================

    def navigate(self):
        """导航到 '我的考试' 页面 (唯一入口)"""
        self.logger.info("导航到: 人员管理 > 我的考试")
        self.navigate_to("人员管理", "我的考试")
        self.wait_vue_stable()
        self.wait_element_visible(self.TABLE)
        return self

    # ==================== Search Area ====================

    def search(self, keyword: str):
        """按考试名称搜索"""
        self.logger.info(f"搜索考试名称: {keyword}")
        input_el = self.wait_element_clickable(self.EXAM_NAME_INPUT)
        input_el.clear()
        input_el.send_keys(keyword)
        self.wait_element_clickable(self.SEARCH_BTN).click()
        self.wait_element_invisible(self.TABLE_LOADING)
        return self

    def reset_search(self):
        """重置搜索条件"""
        self.logger.info("重置搜索条件")
        self.wait_element_clickable(self.RESET_BTN).click()
        self.wait_element_invisible(self.TABLE_LOADING)
        return self

    def select_status(self, status_text: str):
        """按考试状态筛选 (未开始 / 进行中 / 已完成)"""
        self.logger.info(f"选择考试状态: {status_text}")
        # 展开下拉
        self.wait_element_clickable(self.EXAM_STATUS_SELECT).click()
        # 等待下拉选项出现
        self.wait_element_visible((By.CSS_SELECTOR, ".el-select-dropdown__item"))
        # 通过文本精准匹配选项
        option_locator = (By.XPATH, f"//div[contains(@class, 'el-select-dropdown')]//span[text()='{status_text}']")
        self.wait_element_clickable(option_locator).click()
        self.wait_element_invisible(self.TABLE_LOADING)
        return self

    # ==================== Table Area ====================

    def get_table_data(self) -> List[Dict[str, str]]:
        """获取表格所有数据行"""
        self.logger.info("获取表格数据")
        rows = self.find_elements(self.TABLE_ROWS)
        table_data = []
        for row in rows:
            cells = row.find_elements(By.CSS_SELECTOR, "td")
            if len(cells) >= 7:
                row_data = {
                    "exam_name": cells[0].text.strip(),
                    "duration": cells[1].text.strip(),
                    "total_score": cells[2].text.strip(),
                    "pass_score": cells[3].text.strip(),
                    "status": cells[4].text.strip(),
                    "start_time": cells[5].text.strip(),
                    "end_time": cells[6].text.strip(),
                }
                table_data.append(row_data)
        return table_data

    def click_row_action(self, row_index: int, action_text: str):
        """点击指定行的操作按钮 (如 '开始考试' / '查看成绩')

        Args:
            row_index: 行索引（从0开始）
            action_text: 按钮显示文本
        """
        self.logger.info(f"点击第 {row_index + 1} 行的操作按钮: {action_text}")
        rows = self.find_elements(self.TABLE_ROWS)
        if row_index >= len(rows):
            raise IndexError(f"行索引 {row_index} 超出范围 (共 {len(rows)} 行)")

        target_row = rows[row_index]
        action_btn = target_row.find_element(By.XPATH, f".//button[.//span[text()='{action_text}']]")
        self.wait_element_clickable(action_btn)
        action_btn.click()
        self.wait_vue_stable()
        return self

    # ==================== Pagination ====================

    def get_pagination_info(self) -> dict:
        """获取分页信息"""
        self.logger.info("获取分页信息")
        try:
            total_text = self.find_element(self.PAGINATION_TOTAL).text
            total = ''.join(filter(str.isdigit, total_text))
            return {"total": int(total) if total else 0}
        except Exception:
            return {"total": 0}

    def go_to_page(self, page_number: int):
        """点击指定页码"""
        self.logger.info(f"跳转到第 {page_number} 页")
        pager_btn = self.find_element((By.XPATH, f"//button[contains(@class, 'number') and text()='{page_number}']"))
        self.wait_element_clickable(pager_btn).click()
        self.wait_element_invisible(self.TABLE_LOADING)
        return self

    # ==================== Dialog Operations ====================

    def open_detail_dialog(self, row_index: int):
        """打开考试详情弹窗 (通过点击'查看'按钮)"""
        self.logger.info(f"打开第 {row_index + 1} 行的考试详情弹窗")
        self.click_row_action(row_index, "查看")
        self.wait_element_visible(self.DIALOG)
        return self

    def close_detail_dialog(self):
        """关闭详情弹窗"""
        self.logger.info("关闭详情弹窗")
        self.wait_element_clickable(self.DIALOG_CLOSE_BTN).click()
        self.wait_element_invisible(self.DIALOG)
        return self

    def confirm_start_exam(self, row_index: int):
        """点击'开始考试'并确认弹窗"""
        self.logger.info(f"确认开始第 {row_index + 1} 行的考试")
        self.click_row_action(row_index, "开始考试")
        self.wait_element_visible(self.CONFIRM_DIALOG)
        self.wait_element_clickable(self.CONFIRM_SUBMIT_BTN).click()
        self.wait_element_invisible(self.CONFIRM_DIALOG)
        self.wait_vue_stable()
        return self


# ============================================
# ====== 自检命令报告 (不可跳过) ======
# ============================================
# 1. ✅ class 是否继承 BasePage？
#    → 是: "class MyExamPage(BasePage):"
# 2. ✅ 无绝对 XPath？
#    → 否: 未使用 //*[@id="app"] 之类的绝对路径
# 3. ✅ 无 time.sleep？
#    → 否: 代码中无任何 time.sleep 调用
# 4. ✅ 无 print()？
#    → 否: 代码中无任何 print 调用
# 5. ✅ 有 navigate() 方法？
#    → 是: "def navigate(self):"
# 6. ✅ 操作方法 return self 支持链式调用？
#    → 是: 所有公开操作方法均返回 self
# ============================================
# 结果: ✅ 全部通过
# ============================================