# ============================================================
# Test: 我的考试模块测试
# Module: personnel
# Page: 我的考试 (my-exam)
# Author: generated by skill: test-script-generator
# ============================================================
import pytest
import allure
from page.personnel_page.MyExamPage import MyExamPage


@allure.epic("人员管理")
@allure.feature("我的考试")
class TestMyExam:
    """我的考试页面测试套件"""

    @allure.story("页面加载")
    @allure.severity(allure.severity_level.BLOCKER)
    @pytest.mark.smoke
    def test_001_page_load(self, my_exam_page: MyExamPage):
        """TC-MYEXAM-001: 页面正常加载"""
        with allure.step("导航到我的考试页面"):
            my_exam_page.navigate()
        with allure.step("验证页面核心元素加载"):
            assert my_exam_page.is_element_visible(my_exam_page.TABLE), "考试列表表格未加载"
            assert my_exam_page.is_element_visible(my_exam_page.PAGINATION), "分页组件未加载"
        with allure.step("验证搜索区元素"):
            assert my_exam_page.is_element_visible(my_exam_page.EXAM_NAME_INPUT), "考试名称搜索框未加载"
            assert my_exam_page.is_element_visible(my_exam_page.EXAM_STATUS_SELECT), "状态筛选下拉框未加载"
            assert my_exam_page.is_element_visible(my_exam_page.SEARCH_BTN), "搜索按钮未加载"
            assert my_exam_page.is_element_visible(my_exam_page.RESET_BTN), "重置按钮未加载"

    @allure.story("页面加载")
    @allure.severity(allure.severity_level.CRITICAL)
    def test_002_page_load_empty(self, my_exam_page: MyExamPage):
        """TC-MYEXAM-003: 页面加载-无考试数据"""
        with allure.step("导航到我的考试页面"):
            my_exam_page.navigate()
        with allure.step("验证空数据状态提示"):
            table_data = my_exam_page.get_table_data()
            if len(table_data) == 0:
                assert my_exam_page.is_element_visible(my_exam_page.TABLE_EMPTY), "空数据时应显示'暂无数据'提示"
            else:
                pytest.skip("当前环境存在考试数据，跳过空数据验证")

    @allure.story("搜索功能")
    @allure.severity(allure.severity_level.CRITICAL)
    @pytest.mark.smoke
    def test_003_search_by_exam_name(self, my_exam_page: MyExamPage):
        """TC-MYEXAM-005: 按考试名称精确搜索"""
        with allure.step("导航到我的考试页面"):
            my_exam_page.navigate()
        with allure.step("获取页面已有考试数据，确定搜索关键词"):
            data_before = my_exam_page.get_table_data()
            assert len(data_before) > 0, "无可用考试数据，请确保存在至少一条考试记录"
            exam_name = data_before[0]["exam_name"]
        with allure.step(f"搜索考试名称: {exam_name}"):
            my_exam_page.search(exam_name)
        with allure.step("验证搜索结果"):
            data_after = my_exam_page.get_table_data()
            assert len(data_after) > 0, f"搜索考试名称'{exam_name}'后结果为'空'，不符合预期"
            for row in data_after:
                assert exam_name in row["exam_name"], f"搜索结果包含用例'{row['exam_name']}'，与搜索关键词'{exam_name}'不匹配"

    @allure.story("搜索功能")
    @allure.severity(allure.severity_level.CRITICAL)
    def test_004_search_fuzzy(self, my_exam_page: MyExamPage):
        """TC-MYEXAM-006: 按考试名称模糊搜索"""
        with allure.step("导航到我的考试页面"):
            my_exam_page.navigate()
        with allure.step("使用模糊关键词搜索"):
            my_exam_page.search("安全")
        with allure.step("验证搜索结果"):
            data_after = my_exam_page.get_table_data()
            for row in data_after:
                assert "安全" in row["exam_name"], f"搜索结果包含'{row['exam_name']}'，应与关键词'安全'匹配"

    @allure.story("搜索功能")
    @allure.severity(allure.severity_level.CRITICAL)
    @pytest.mark.smoke
    def test_005_filter_by_status(self, my_exam_page: MyExamPage):
        """TC-MYEXAM-007: 按考试状态筛选"""
        with allure.step("导航到我的考试页面"):
            my_exam_page.navigate()
        with allure.step("重置筛选条件，确保起始状态一致"):
            my_exam_page.reset_search()
        with allure.step("获取所有数据的状态分布"):
            data_all = my_exam_page.get_table_data()
            statuses = set(row["status"] for row in data_all)
            if len(statuses) <= 1:
                pytest.skip("数据状态单一，无法验证筛选功能")

        for status in ["未开始", "进行中", "已完成"]:
            with allure.step(f"筛选状态: {status}"):
                my_exam_page.select_status(status)
                filtered_data = my_exam_page.get_table_data()
                for row in filtered_data:
                    assert row["status"] == status, f"筛选后数据行'{row['exam_name']}'的状态为'{row['status']}'，预期为'{status}'"

    @allure.story("分页功能")
    @allure.severity(allure.severity_level.CRITICAL)
    @pytest.mark.smoke
    def test_006_pagination_info(self, my_exam_page: MyExamPage):
        """TC-MYEXAM-013: 分页-基本信息"""
        with allure.step("导航到我的考试页面"):
            my_exam_page.navigate()
        with allure.step("验证分页组件信息"):
            pagination_info = my_exam_page.get_pagination_info()
            total = pagination_info["total"]
            assert total >= 0, f"分页总条数应为非负整数，实际为: {total}"
            if total <= 0:
                pytest.skip("当前无数据，跳过分页信息详细验证")
            else:
                assert my_exam_page.is_element_visible(my_exam_page.PAGINATION), "分页组件应一直可见"

    @allure.story("分页功能")
    @allure.severity(allure.severity_level.CRITICAL)
    def test_007_pagination_page_jump(self, my_exam_page: MyExamPage):
        """TC-MYEXAM-015: 分页-跳转"""            
        with allure.step("导航到我的考试页面"):
            my_exam_page.navigate()
        with allure.step("检查是否存在分页"):
            pagination_info = my_exam_page.get_pagination_info()
            if pagination_info["total"] <= 20:
                pytest.skip("总数据量不足一页，无法进行跳转到第二页的测试")
        with allure.step("获取第一页数据并跳转到第二页"):
            page_one_data = my_exam_page.get_table_data()
            first_record_p1 = page_one_data[0]["exam_name"]
            my_exam_page.go_to_page(2)
        with allure.step("验证跳转后的页面内容不同"):
            page_two_data = my_exam_page.get_table_data()
            assert len(page_two_data) > 0, "跳转到第二页后表格数据为空"
            assert page_two_data[0]["exam_name"] != first_record_p1, "第二页的第一个记录不应与第一页相同"

    @allure.story("弹窗操作")
    @allure.severity(allure.severity_level.CRITICAL)
    def test_008_open_detail_dialog(self, my_exam_page: MyExamPage):
        """TC-MYEXAM-0xx: 打开考试详情弹窗"""
        with allure.step("导航到我的考试页面"):
            my_exam_page.navigate()
        with allure.step("验证存在可操作的数据"):
            data = my_exam_page.get_table_data()
            assert len(data) > 0, "无可用考试数据，请确保存在至少一条考试记录"
        with allure.step("点击第一行的'考试详情'按钮"):
            my_exam_page.click_row_action(0, "详情")
        with allure.step("验证弹窗出现"):
            assert my_exam_page.is_element_visible(my_exam_page.DIALOG), "弹窗应该出现"
            assert my_exam_page.is_element_visible(my_exam_page.DIALOG_TITLE), "弹窗标题应该可见"
        with allure.step("关闭弹窗"):
            my_exam_page.find_element(my_exam_page.DIALOG_CLOSE_BTN).click()
            assert my_exam_page.is_element_invisible(my_exam_page.DIALOG), "弹窗应该关闭"

    @allure.story("弹窗操作")
    @allure.severity(allure.severity_level.CRITICAL)
    def test_009_confirm_start_exam(self, my_exam_page: MyExamPage):
        """TC-MYEXAM-018: 确认开始考试"""            
        with allure.step("导航到我的考试页面"):
            my_exam_page.navigate()
        with allure.step("定位并点击'开始考试'按钮"):
            data = my_exam_page.get_table_data()
            start_exam_row_index = None
            for i, row in enumerate(data):
                if row["status"] == "未开始":
                    start_exam_row_index = i
                    break
            if start_exam_row_index is None:
                pytest.skip("未找到状态为'未开始'的考试数据，跳过确认开始考试测试")
            my_exam_page.click_row_action(start_exam_row_index, "开始考试")
        with allure.step("验证确认弹窗出现"):
            assert my_exam_page.is_element_visible(my_exam_page.CONFIRM_DIALOG), "确认开始考试弹窗应该出现"
        with allure.step("点击取消按钮，不真正开始考试"):
            my_exam_page.find_element(my_exam_page.CONFIRM_CANCEL_BTN).click()
            assert my_exam_page.is_element_invisible(my_exam_page.CONFIRM_DIALOG), "确认弹窗应该关闭"